name: "clip_text_encoder"
platform: "tensorrt_plan"
max_batch_size: 256

input [
  { name: "text" data_type: TYPE_INT32 dims: [77] }
]

output [
  { name: "text_embedding" data_type: TYPE_FP32 dims: [512] }
]

instance_group [
  { kind: KIND_GPU count: 1 }
]

optimization {
  execution_accelerators {
    gpu_execution_accelerator: [
      { name: "tensorrt" parameters { key: "precision_mode" value: "FP16" } }
    ]
  }
}
