FROM nvcr.io/nvidia/tritonserver:25.06-py3

WORKDIR /workspace

RUN pip install --no-cache-dir uv
COPY pyproject.toml ./

RUN uv pip install --system --break-system-packages .

COPY builder ./builder
COPY common ./common


ENV TRITON_MODEL_REPOSITORY=/models
ENV TRITON_ALLOW_HTTP=true
ENV TRITON_ALLOW_GRPC=true


EXPOSE 8000 8001 8002

CMD sh -c "tritonserver \
    --model-repository=${TRITON_MODEL_REPOSITORY} \
    --model-control-mode=explicit \
    --load-model=* \
    --allow-http=${TRITON_ALLOW_HTTP} \
    --allow-grpc=${TRITON_ALLOW_GRPC}"
